var tl = gsap.timeline()
tl.from("h3",{
    y:-50,
    opacity:0,
    delay:.4,
    duration:0.5,
    stagger:0.4
})
tl.from("h1",{
    x:-500,
    opacity:0,
    duration:1,
    stagger:0.4
})
tl.from("img",{
    x:100,
    opacity:0,
    duration:.4,
    stagger:0.4,
    rotate:45
})